### ISSUE TITLE
推荐多一个VPN

### ISSUE THREAD

**Issue by ken30huang** [SunLn/SunLn-F2E-Bookmarks#4]
你上面那些vpn链接好多都访问不了
http://cdn2.cloudlink.net.cn:8080/

**Comment by JiangJoy** [comment]
sry，没明白。
________________________________
发件人: Ken.Wong <notifications@github.com>
发送时间: 2018年4月12日 9:45
收件人: SunLn/SunLn-F2E-Bookmarks
抄送: Subscribed
主题: [SunLn/SunLn-F2E-Bookmarks] 推荐多一个VPN (#4)


你上面那些vpn链接好多都访问不了
http://cdn2.cloudlink.net.cn:8080/

―
